# Assignment-2

This notebook contains the coding questions to test the proficiency in `NumPy` library of python.

### Date: 7th December, 2025

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the questions in the notebook and save it.
- Rename the file as `Assignment-02-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-02-Dipika_Chopra.ipynb`.
- Upload the solved notebook in your github repo under the folder **Assignment-2**.
- Upload the solved notebook in the google drive location: https://drive.google.com/drive/folders/163Prhhe78pDrm7EQJmU6puuRQJ2agxzl?usp=drive_link 

<h3><span style="color:red"> Deadline: 21st December, 2025 </span></h3>

In [2]:
import numpy as np

## Problem: 1
Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [137]:
# Write your code here
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

## Problem: 2

Generate an array of length $3n$ , filled with the cyclic pattern 1, 2, 3. Where $n$ is a natural number.

In [118]:
# Write your code here
def array_len(n):
    return np.tile((1,2,3), n)

array_len(3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

## Problem: 3
Create an array of the first $n$ odd integers. $n$ is a natural number input from user.

In [131]:
# Write your code here
np.array(range(1, 2 * int(input("Enter the natural number")) + 1, 2))


array([1, 3, 5, 7, 9])

## Problem: 4

Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [139]:
# Write your code here
arr = np.ones((10, 10)) 
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Problem: 5

Create an 8 x 8 array with a checkerboard pattern of zeros and ones.

In [ ]:
# Write your code here



## Problem: 6

Create an array $x$ with 100 points in the interval $[-1,1]$ (the points must be uniformly spaced). Then create another array $y$. 

Where $y = x^2 sin(x^2) + x$. 

Try to plot $y$ vs $x$ using matplotlib.

In [69]:
# Write your code here

import matplotlib.pyplot as plt

x = np.arange(-1, 1, 0.02)
y = (x**2 * np.sin(x ** 2)) + x

plt.figure(figsize = (10,4))
plt.scatter(x, y)
plt.xlabel("x")
plt.ylabel("y")
plt.show()

## Problem: 7 
Create a function which creates an $n×n$ array with $(i , j)$ -entry equal to $i+ j$

In [23]:
# Write your code here
def sum_table(n):
    col = np.arange(n)
    row = np.arange(n).reshape(n, 1)
    return row + col

sum_table(8)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])

# Problem: 8
Evaluate $cos$ and $sin$ on the interval $[0,1]$  with 1000 points and then stack the results into a tall array with rows being the $(cos(x),sin(x))$ entries.

In [4]:
# Write your code here


# Problem: 9

Create a random $3×5$ array using the `np.random.rand(3 ,5)` function and compute: the sum of all the entries, the sum of the rows, and the sum of the columns.

In [ ]:
# Write your code here



## Problem: 10

Create a random $5×5$ array using the function `np.random.rand(5, 5)`. Then sort the rows according to the second column.

In [136]:
# Write your code here
np.random.rand(5, 5)

array([[0.86401762, 0.80914398, 0.95122236, 0.21793102, 0.92080287],
       [0.07828366, 0.31568379, 0.33440333, 0.13846505, 0.02237028],
       [0.73172001, 0.28731041, 0.6380901 , 0.37365199, 0.86404241],
       [0.1182222 , 0.77881217, 0.12412772, 0.34879335, 0.47159354],
       [0.10297801, 0.77011306, 0.59356496, 0.27900737, 0.08584325]])