In [1]:
import numpy as np

In [5]:
np.array(range(0,100, 5))

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [3]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
np.zeros((4,), dtype="int")

array([0, 0, 0, 0])

In [10]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.empty((5,))

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.33511018e-306,
       3.44886448e-307])

In [17]:
v = np.array(([1,2,3],[4,5,6],[7,8,9]))
v.shape

(3, 3)

In [20]:
np.zeros_like(v)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.arange(start=0, stop=12, step=3)

array([0, 3, 6, 9])

In [ ]:
np.array(range(0,12,3))

array([0, 3, 6, 9])

: 